language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - ./gradlew testMockDebugUnitTestCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
